# Developed by Eng Mouaz M AlShahmeh
name: meta_seo_with_go_router_example
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  meta_seo: ^2.0.2 # TODO::add this dependency
  go_router: ^6.0.7 # TODO::add this dependency with latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
